[package]
name = "table-enum-core"
version = "0.1.0"
edition = "2021"
authors = ["CÃ©sar Santos <cesar.santos.1990@gmail.com>"]

[dependencies]
quote = "1.0.29"
syn = { version = "2.0.25", features = ["extra-traits", "full"] }
proc-macro2 = "1.0.29"
proc-macro-error = "1.0.4"