[package]
name = "table-enum-macro"
version = "0.1.0"
edition = "2021"
authors = ["CÃ©sar Santos <cesar.santos.1990@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.64"
table-enum-core = { path = "../table-enum-core" }
